import { AgentMemory } from '@ai-video-editor/shared';

export class AgentMemoryService {
  private static memories = new Map<string, AgentMemory>();

  /**
   * Retrieves or instantiates memory context for a project.
   */
  public static getMemory(projectId: string): AgentMemory {
    let mem = this.memories.get(projectId);
    if (!mem) {
      mem = {
        projectId,
        context: {
          conversationHistory: [],
          assets: [],
        },
        intermediateOutputs: {},
      };
      this.memories.set(projectId, mem);
    }
    return mem;
  }

  /**
   * Appends an entry into a project's conversation logs.
   */
  public static logConversation(
    projectId: string,
    role: 'user' | 'assistant',
    content: string,
  ): void {
    const mem = this.getMemory(projectId);
    mem.context.conversationHistory.push({ role, content });
  }

  /**
   * Saves intermediate output generated by an agent (e.g. script copy, storyboard sequences, etc.).
   */
  public static saveIntermediateOutput(projectId: string, key: string, value: any): void {
    const mem = this.getMemory(projectId);
    mem.intermediateOutputs[key] = value;
  }

  /**
   * Retrieves intermediate output.
   */
  public static getIntermediateOutput(projectId: string, key: string): any | null {
    const mem = this.getMemory(projectId);
    return mem.intermediateOutputs[key] || null;
  }

  /**
   * Clears memory context for a project.
   */
  public static clearMemory(projectId: string): void {
    this.memories.delete(projectId);
  }
}
